### ISSUE TITLE
rkon-core MIT license

### ISSUE THREAD

**Issue by Kronos666** [JBoxman7/insAdmin#1]
You are using the code of rkon-core in this repository which is licensed under the MIT license, but you are not including the LICENSE file of rkon-core (which can be found in the original repo at [https://github.com/Kronos666/rkon-core/blob/master/LICENSE](https://github.com/Kronos666/rkon-core/blob/master/LICENSE)).

This is breaking the conditions of the MIT license, please include this file in your repository.

**Comment by JBoxman7** [comment]
I didn't know how to set your jar as a dependency for my program until recently, so I just copied it over for the time being. Didn't mean to push it like this. Plus, I've got sensitive information in the same version, so it'll come down anyway.
